# Generated by Django 3.2 on 2023-03-28 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_marca_producto'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='tbl_producto',
        ),
    ]
