# Generated by Django 3.2 on 2023-03-28 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_producto_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoRelacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Principal', to='web.producto')),
                ('relacionado', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Relacionado', to='web.producto')),
            ],
            options={
                'db_table': 'tbl_producto_relacionado',
            },
        ),
        migrations.CreateModel(
            name='ProductoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, upload_to='galeria')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.producto')),
            ],
            options={
                'db_table': 'tbl_producto_imagen',
            },
        ),
    ]
